### ISSUE TITLE
[BUG] need to update minimatch version from 3.0.4 to higher in library's package.json

### ISSUE THREAD

**Issue by ngfx** [Tinkoff/ng-morph#48]
# 🐞 Bug report

### Description

minimatch 3.0.4 is discovered to have a high severity vulnerability (by WhiteSource). Please upgrade to higher version (at least 3.0.5) and update the dependency list in https://github.com/Tinkoff/ng-morph/blob/main/libs/ng-morph/package.json

### Versions

- Package 2.1.1

**Comment by feitzi** [comment]
It seems that this issue was already resolved in pull request #44, but the fix has not been released yet. @IKatsuba, would you be able to create a new release that includes this fix?

**Comment by edbzn** [comment]
Hi, we are facing it too in 3 of our packages, and our users are reporting it. It would be great to release ng-morph @IKatsuba.

**Comment by IKatsuba** [comment]
@edbzn  I will! Thank you guys!
